### ISSUE TITLE
How to create custom 'train_words_index.txt'

### ISSUE THREAD

**Issue by jkaewprateep** [pannous/tensorflow-speech-recognition#10]
I would like to know how to get this sequence number (2 42 14 66 93 19 46 42 24 43 49 3)?

In train_words_index.txt there are number of lines of the word and sequence number like this
'measurement_Victoria_160.wav.png	2 42 14 66 93 19 46 42 24 43 49 3'. I had try to find the way to create this sequence number many where but couldn't be found

Thank you in advance,

**Comment by pannous** [comment]
You can use any text to phoneme program/engine.
The exact numbers don't matter they are only an internal representation.
