### ISSUE TITLE
How to augment data for the spectogram?

### ISSUE THREAD

**Issue by yasumi88** [pannous/tensorflow-speech-recognition#11]
Any sample code to do data augmentation on the spectrograms?
Observed that for spectrogram words, they are mainly in 160 format. How do you get other variations such as 40, 60 +? What kind of transformation is that?

Thanks!

**Comment by pannous** [comment]
No sample code here, but it's a fairly easy task.

**Comment by yasumi88** [comment]
How is it done? still learning about this field :)
