### ISSUE TITLE
could not able to run the pannous/tensorflow-speech-recognition

### ISSUE THREAD

**Issue by roshankarwalkar1** [pannous/tensorflow-speech-recognition#12]
sorry sir , but i have tried a lot to run your application on my system but i am unable to run it on my local system so please help me to run it on my local system i have already installed the setup of python based tensorflow on my system.

**Comment by qinglintian** [comment]
yeah, I think the read me can be improved. there are quite a lot commented lines in the code and don't know how to get started

**Comment by shrisggs** [comment]
same problem with me also i am also not able to run the system on my local linux platform so please help us as fast as possible

**Comment by pannous** [comment]
made some improvement code 
 did it help?
