### ISSUE TITLE
How to classify a entire sentence.

### ISSUE THREAD

**Issue by Tinet-AaronAn** [pannous/tensorflow-speech-recognition#15]
I have many sounds that WAV format. The duration is about 10 seconds. All the wav is one of the ten sentences. For example: "The number you have dialed is power off"/"dialed number is not exist"/ some other sentences. Is it suitable to use your project to do this?

**Comment by shrisggs** [comment]
are you able to run the example?

**Comment by shrisggs** [comment]
if yes please help me to do the same

**Comment by Tinet-AaronAn** [comment]
not run yet.
