### ISSUE TITLE
python number_classifier_tflearn.py hangs on wrong path instead of raising error and take long time to get the data

### ISSUE THREAD

**Issue by shrisggs** [pannous/tensorflow-speech-recognition#17]
Hi all, awesome project! I checked it out and wasn't able to run the classification procedure.

Running 
python  number_classifier_tflearn.py causes the code to run properly up to some line and then hangs out for long time and then capture the mouse while hang out.

**Comment by ghatul** [comment]
yaaa shrisggs i am also unable to run pannous please help us as fast as possible

**Comment by pannous** [comment]
sorry for late reply, fixed now
