### ISSUE TITLE
Speaker Classification Clarification

### ISSUE THREAD

**Issue by AKBoles** [pannous/tensorflow-speech-recognition#18]
Hello, I was investing your speaker classification example that uses TFLearn. I had a question about the test audio sample that was used to test the model. I may be mistaken, but I believe that this sample is inside the training set which would not be ideal for testing. Why is this (or isn't this if I am wrong) done?

Thank you in advance for your help!

**Comment by pannous** [comment]
It's just a toy example, so it's not that important to get the accurate test-score.
