### ISSUE TITLE
License of the project

### ISSUE THREAD

**Issue by a-rodin** [pannous/tensorflow-speech-recognition#2]
Hi!
What license does the project have? Also who is meant to be the copyright owner for the code commited to the project by third party developers?

**Comment by pannous** [comment]
project is free for all open source projects and small independent businesses up to 3 employees.

**Comment by a-rodin** [comment]
@pannous Could you specify what exactly [free software license(s)](https://www.gnu.org/licenses/license-list.en.html) do you use for this project? Some of free software license are incompatible between each other, so lack of `COPYING` of `LICENSE` file leads to ambiguities and potential problems for free software projects that attempt to use your code.

**Comment by pannous** [comment]
Thanks,  haven't picked one yet.
Probably going with a modified #GNUGPLv3
