### ISSUE TITLE
spoken_words url broken

### ISSUE THREAD

**Issue by anees042** [pannous/tensorflow-speech-recognition#20]
the url spoken_words is broken
`
Downloading from http://pannous.net/files/spoken_words to data/spoken_words
Traceback (most recent call last):
  File "speaker_classifier_tflearn.py", line 17, in <module>

urllib.error.HTTPError: HTTP Error 404: Not Found`

**Comment by pannous** [comment]
thx

**Comment by elizacamber** [comment]
seems to be broken again
