### ISSUE TITLE
Error When Run densenet_layer.py

### ISSUE THREAD

**Issue by ragipunal** [pannous/tensorflow-speech-recognition#21]
Hello Everybody, 
I have a problem.
./number_classifier_tflearn.py ./speaker_classifier_tflearn.py run and success but densenet_layer.py not working
I follow this steps on docker.

docker run -it -v C:\WorkData\GitRespostory\tensorflow-speech-recognition:/tf_speech gcr.io/tensorflow/tensorflow:latest-devel

after on shell command screen show

cd /tensorflow
git pull

then run this steps

apt-get update
apt-get install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
cd /tf_speech
pip install -r requirements.txt
pip install h5py
pip install librosa

Note: spoken_words.tar file manuel download and copy to folder.
and now
python densenet_layer.py

but show this error, please help me.

`Traceback (most recent call last):
  File "densenet_layer.py", line 69, in <module>
    net.train(data=batch,batch_size=10,steps=5000,dropout=0.6,display_step=10,test_step=100) # run
  File "/tf_speech/layer/net.py", line 385, in train
    loss,_= session.run([self.cost,self.optimizer], feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 943, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (10, 262144) for Tensor u'data/Placeholder:0', which has shape '(?, 4096, 4096)'`

**Comment by pannous** [comment]
Thanks for reporting! 
It is fixed now.
