### ISSUE TITLE
multiple problems with speech2text-seq2seq.py

### ISSUE THREAD

**Issue by anees042** [pannous/tensorflow-speech-recognition#24]
Broken dependency "sugartensor" not in requirements.txt

AND

"tensorflow.examples.tutorials" not available in windows install of tensorflow, needs to be copied manually from git repo of tensorflow.

AND

Line 13, "Update:" needs to be commented in speech2text-seq2seq.py

AND

`Traceback (most recent call last):
  File "speech2text-seq2seq.py", line 65, in <module>
    z = x.sg_conv1d(size=1, dim=num_dim, act='tanh', bn=True)
AttributeError: 'list' object has no attribute 'sg_conv1d'`

OS: Windows 10,
TensorFlow: 0.12
Python: 3.5

**Comment by pannous** [comment]
read the text below "Update" and see why it's not commended ;)

**Comment by anees042** [comment]
thanks for the information and help, it's useful.
