### ISSUE TITLE
missing import in speech2text-tflearn.py

### ISSUE THREAD

**Issue by anees042** [pannous/tensorflow-speech-recognition#26]
missing import for librosa in speech2text-tflearn.py

also require python-tk to be installed through apt-get

**Comment by pannous** [comment]
thanks for pointing this out.

 the librosa dependency was added

 couldn't find any python-tk dependency though!?

**Comment by anees042** [comment]
Thanks @pannous, it was asking me to install python-tk on ubuntu 16.04. anyway i will recheck. once again thanks for your effort.
