### ISSUE TITLE
data download link is broken for words test data?

### ISSUE THREAD

**Issue by yasumi88** [pannous/tensorflow-speech-recognition#3]
Any other alternative download link for the data?
I tried clicking the link provided in the source file and in caffe's implementation but to no avail:
https://www.dropbox.com/s/eb5zqskvnuj0r78/spoken_words.tar?dl=0

Thanks!

**Comment by pannous** [comment]
Hi,  thanks for pointing it out. we know fix the link :
https://dl.dropboxusercontent.com/u/23615316/spoken_words.tar

**Comment by naiyeleo** [comment]
The new link is also not available. Could you provide a new link?
Thanks!

**Comment by TylerLafayette** [comment]
+1 The Dropbox links aren't working for me either.
Thanks!

**Comment by SYnchronYSe** [comment]
+1
