### ISSUE TITLE
What should dtype of placeholder y_ in training be?

### ISSUE THREAD

**Issue by yasumi88** [pannous/tensorflow-speech-recognition#4]
From speech_encoder.py, 
`batch_xs, batch_ys = speech.train.next_batch(100)`
`batch_xs=[flatten(matrix) for matrix in batch_xs]`
`feed = {x: batch_xs, y_: batch_ys}`

The above has the following error:
> ValueError: invalid literal for float(): 2 14 68 6 32 14 73 6 47 14 73 3

What should placeholder of y_ be?

Thanks!

**Comment by pannous** [comment]
bug fixed
