### ISSUE TITLE
record my own voice

### ISSUE THREAD

**Issue by Hitesh95** [pannous/tensorflow-speech-recognition#47]
can anyone tell me how do i record my own voice and where we should put it so that we get speech to text converted??

**Comment by gowthambalusamy** [comment]
Lets try this ...
[https://github.com/facebookresearch/loop](
https://github.com/facebookresearch/loop)

**Comment by pannous** [comment]
modify ./record.py

sorry the final version of this project was abandoned,
 checkout https://github.com/mozilla/DeepSpeech
