### ISSUE TITLE
Where is requirements.txt file?

### ISSUE THREAD

**Issue by tarasinf** [pannous/tensorflow-speech-recognition#5]
Who has successfully found requirements.txt file?

**Comment by ahmaurya** [comment]
+1

**Comment by dare0021** [comment]
I looked through the commits and it was never there

**Comment by llSourcell** [comment]
??

**Comment by llSourcell** [comment]
@pannous

**Comment by llSourcell** [comment]
i'd like to make a video about this repo. but i need to be able to get it to work :) 

www.youtube.com/c/sirajology .

@pannous  let me know if this ever gets fixed

**Comment by pannous** [comment]
sorry for wasting your guy's energy, it is added now.
 and sorry for the late reply.

There are now working number_classifier and speaker_classifier scripts.
however please note that this project is still in the experimental phase, 
don't expect to be able to fluently dictate to your your linux just yet.
