### ISSUE TITLE
can people tell me in what order to run these codes? 

### ISSUE THREAD

**Issue by john81529** [pannous/tensorflow-speech-recognition#50]
I study these codes recently,but i do not konw which code should i run first,and next.can someone help me?please

**Comment by laixl** [comment]
Make sure you have installed the requirements firstly.
Run the following code in terminal.
python number_classifier_tflearn.py
This is for a simple example about digits classifier(0-9 English digits). 
Then run the code.
python speaker_classifier_tflearn.py
This is for a simple example about speakers classifier(15 speakers).
Try to understand the codes.

**Comment by john81529** [comment]
Thank you.However,there are other codes,how to run them?
