### ISSUE TITLE
How to use this code for real-time recognition?

### ISSUE THREAD

**Issue by JrSurapaneni** [pannous/tensorflow-speech-recognition#66]
This code is working brilliantly for saved audio files , how to make it work for real-time scenarios. Like User speaks and it recognize spoken digits.

**Comment by nitishxp** [comment]
@JrSurapaneni did u able to get real-time recognition?

**Comment by JrSurapaneni** [comment]
I trained it, prepared a model which could predict pre-recorded samples at 30% accuracy. I dont think it can be utilized as realtime model.
