### ISSUE TITLE
format of file in /data/speech

### ISSUE THREAD

**Issue by handsomefun** [pannous/tensorflow-speech-recognition#7]
could you like to give an example of file in /data/speech?

**Comment by handsomefun** [comment]
like http://pannous.net/spoken_numbers.tar?

**Comment by pannous** [comment]
the speech_data.py script should fetch all the files that you need.

**Comment by Mithul** [comment]
The speech_data.py tries to fetch it form [http://pannous.net/files/spoken_numbers.tar]( http://pannous.net/files/spoken_numbers.tar) instead of  [http://pannous.net/spoken_numbers.tar](http://pannous.net/spoken_numbers.tar)

**Comment by pannous** [comment]
thx
